# Conclusion

We have shown factors connected to negative opinions towards China, and analyzed them on both individual and national scales. The results suggest that both covid and socio-economic factors have an effect on the increasing negative impact on China. However, it is suggested that covid itself further pushed opinions to the negative side, and certain covid-related factors are significant on both individual and national scales.

One limitation is that most plots give correlational information, and to address that we tried to inject more causal information through different dimensions of analysis. One example is analyzing not just current atittudes, but also attitudes across time along with other variables, such as one variable that is significant across all experiments: opinion on how China handled covid. Even so, the limitation remains and we should be encouraged to think beyond what the data represents. There could always be an omitted variable bias, that is, something latent that leads to both negative thinking about the way China handled covid and opinion towards China in general. A future direction is thinking about what could these latent variables be. Possible candidates include the perception of democracy and the culture of media, which could lead to criticism against both China's stoic covid policies and China itself.