--- 
title: "Factors Behind Global Opinions"
author: "Xingyu Wei, Liyi Zhang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

Covid-19 significantly impacts world politics, and China has become an increasingly prominent player on the world stage. This project studies major factors that influence global attitudes toward China, and examines the ways these factors interact with each other. It is clear that global public opinions toward China dropped significantly as measured before and after covid. We investigate how covid’s effect on individuals and factors other than covid interact to influence opinions toward China. Specifically, we discover that the impact of factors differ when applied to individuals or countries. Economic situation, how much covid impact livelihood, and perception on how China handled covid are significant in influencing individual opinions. However, only perception on how China handled covid correlates whether a country overall tends more to favor or disfavor China.

We draw inspirations from a similar study conducted by the Pew Research Center: [Unfavorable Views of China Reach Historic Highs in Many Countries](https://www.pewresearch.org/global/2020/10/06/unfavorable-views-of-china-reach-historic-highs-in-many-countries/). Both studies identify factors connected with increasingly negative views towards China. However, our study differs by analyzing factors on an individual level, whereas the original study analyzes national trends. Additionally, our study features interactions among three or more variables that are absent in the original study. 